<?php
namespace app\test;
/**
 * DO NOT EDIT THIS FILE
 * tests_dba_user 表 role 字段的 PHP enum 类型
 * @package test
 */
enum Tests_Dba_User_Role_Enum: string{
    case MANAGER = 'manager';
    case ADMIN = 'admin';
    case WAREHOUSE = 'warehouse';
}
