<?php
namespace app\test;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \yangzie\Column;

/**
 * DO NOT EDIT THIS FILE
 * 单元测试表 tests_db_ctx 的 model 映射（分库上下文测试使用，同时适用于分表 tests_db_ctx_x）
 * 测试库/表由 app\modules\test\Tests_Db 统一创建，测试中直接使用本类即可
 * @package test
 * @property int $id
 * @property ?string $name
 */
class Tests_Db_Ctx_Model extends YZE_Model{
    use Tests_Db_Ctx_Method;

    const TABLE = "tests_db_ctx";
    const MODULE_NAME = "test";
    const KEY_NAME = "id";
    const UUID_NAME = "uuid";

    /**
     * @var int
     */
    #[Column(type: 'int', nullable: false, length: 11)]
    private int $id;

    /**
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 45)]
    private ?string $name;

    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array();

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array();

    /**
     * 返回每个字段的描述文本
     * @param $column
     * @return mixed
     */
    public function get_column_mean($column){
        switch ($column){
        case "id": return "id";
        case "name": return "name";
        default: return $column;
        }
    }
}
?>
