<?php
namespace app\test;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \yangzie\Column;

/**
 * DO NOT EDIT THIS FILE
 * 单元测试表 tests_dba_user 的 model 映射
 * 测试库/表由 app\modules\test\Tests_Db 统一创建，测试中直接使用本类即可
 * @package test
 * @property int $id
 * @property string $created_on
 * @property string $name
 * @property Tests_Dba_User_Role_Enum $role
 * @property float $price
 * @property ?string $email
 */
class Tests_Dba_User_Model extends YZE_Model{
    use Tests_Dba_User_Method;

    const TABLE = "tests_dba_user";
    const MODULE_NAME = "test";
    const KEY_NAME = "id";
    const UUID_NAME = "uuid";

    /**
     * @var int
     */
    #[Column(type: 'int', nullable: false, length: 11)]
    private int $id;

    /**
     * @var string
     */
    #[Column(type: 'date', nullable: false, default: 'CURRENT_TIMESTAMP')]
    private string $created_on;

    /**
     * @var string
     */
    #[Column(type: 'string', nullable: false, length: 45)]
    private string $name;

    /**
     * @var Tests_Dba_User_Role_Enum
     */
    #[Column(type: 'enum', nullable: false)]
    private Tests_Dba_User_Role_Enum $role;

    /**
     * @var float
     */
    #[Column(type: 'float', nullable: false, length: 10, default: '0.00')]
    private float $price;

    /**
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 100)]
    private ?string $email;

    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array("email" => "email");

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array();

    /**
     * 返回每个字段的描述文本
     * @param $column
     * @return mixed
     */
    public function get_column_mean($column){
        switch ($column){
        case "id": return "id";
        case "created_on": return "created_on";
        case "name": return "name";
        case "role": return "role";
        case "price": return "price";
        case "email": return "email";
        default: return $column;
        }
    }
}
?>
