<?php
namespace app\test;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \yangzie\Column;

/**
 * DO NOT EDIT THIS FILE
 * 单元测试表 yze_encrypt_test 的 model 映射（CLI 加密字段生成测试使用的表）
 * 测试库/表由 app\modules\test\Tests_Db 统一创建，测试中直接使用本类即可
 * @package test
 * @property int $id
 * @property string $password
 * @property ?string $memo
 * @property ?string $other
 */
class Yze_Encrypt_Test_Model extends YZE_Model{
    use Yze_Encrypt_Test_Method;

    const TABLE = "yze_encrypt_test";
    const MODULE_NAME = "test";
    const KEY_NAME = "id";
    const UUID_NAME = "uuid";

    /**
     * @var int
     */
    #[Column(type: 'int', nullable: false)]
    private int $id;

    /**
     * @var string
     */
    #[Column(type: 'string', nullable: false, length: 45, default: '')]
    private string $password;

    /**
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 100)]
    private ?string $memo;

    /**
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 45)]
    private ?string $other;

    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array();

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array();

    /**
     * 返回每个字段的描述文本
     * @param $column
     * @return mixed
     */
    public function get_column_mean($column){
        switch ($column){
        case "id": return "id";
        case "password": return "password";
        case "memo": return "memo";
        case "other": return "other";
        default: return $column;
        }
    }
}
?>
