<?php
namespace app\test;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \yangzie\Column;

/**
 * DO NOT EDIT THIS FILE
 * 单元测试表 yze_encrypt_e2e 的 model 映射（dba.php 字段加密端到端测试使用）
 *
 * 测试目的：
 *  - password / token 通过 Column 注解声明为加密字段；
 *  - name 作为非加密字段，用于对比存储内容；
 *  - secret_note 用于 NULL 加密字段的往返。
 *
 * 测试库/表由 app\modules\test\Tests_Db 统一创建，测试中直接使用本类即可。
 *
 * @package test
 * @property int $id
 * @property string $name
 * @property string $password
 * @property ?string $token
 * @property ?string $secret_note
 */
class Yze_Encrypt_E2e_Model extends YZE_Model{
    use Yze_Encrypt_E2e_Method;

    const TABLE = "yze_encrypt_e2e";
    const MODULE_NAME = "test";
    const KEY_NAME = "id";
    const UUID_NAME = "uuid";

    /**
     * @var int
     */
    #[Column(type: 'int', nullable: false, length: 11)]
    private int $id;

    /**
     * @var string
     */
    #[Column(type: 'string', nullable: false, length: 45)]
    private string $name;

    /**
     * 加密字段：save 时由 dba.php 自动加密落库，load 时由 dba.php 自动解密回填
     *
     * @var string
     */
    #[Column(type: 'string', nullable: false, length: 255, encrypt: true)]
    private string $password;

    /**
     * 加密字段，可空；用于 NULL 加密字段的往返
     *
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 255, encrypt: true)]
    private ?string $token;

    /**
     * 加密字段，可空；用于 NULL 加密字段的往返
     *
     * @var ?string
     */
    #[Column(type: 'string', nullable: true, length: 512, encrypt: true)]
    private ?string $secret_note;

    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array();

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array();

    /**
     * 返回每个字段的描述文本
     * @param $column
     * @return mixed
     */
    public function get_column_mean($column){
        switch ($column){
        case "id": return "id";
        case "name": return "name";
        case "password": return "password";
        case "token": return "token";
        case "secret_note": return "secret_note";
        default: return $column;
        }
    }
}
?>